### ISSUE TITLE
how add progress bar?

### ISSUE THREAD

**Issue by wangdemon** [FalsinSoft/Q7z#1]
How can progress bars be displayed like 7Z software

![1](https://github.com/FalsinSoft/Q7z/assets/20681339/eec79b27-a37d-4406-80ac-6d4b017b9064)

**Comment by FalsinSoft** [comment]
The cpp interface code developed by the autor is basically composed by many methods to manage files to/from the archive. Surely it will be possible to "extract" info about the creation/extraction process on real time but is not a very trivial modify. I can try to work on it, but not anytime soon, I'm sorry...

**Comment by FalsinSoft** [comment]
Just committed the change to get the progress status of the operation. Please check the demo sources to better understand the use.
